-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFoAYZZqiyrTYmrju
GftyRtWTuhsZ4XmPQJMgndHlRBigCgYIKoZIzj0DAQehRANCAARsl9DifKiJU/bV
nnyQuCGvepvBWomTQLrVbvOs1ifwpBTtH1HQBwPoGUs4cdSJd5XpOGpPSGVzcL98
Stgga7bM
-----END PRIVATE KEY-----